Repository mixxxdj/manual, pull requests merged in 2020-12, with the labels that each got.

#312 appendix: fix ref to library/file-format-compatibility
  source/chapters/appendix.rst
  source/chapters/library.rst
Labels: bug

#318 library: Replace table in "Using search operators" section
  source/chapters/library.rst
Labels: enhancement

#319 Fix tables
  source/_static/css/mixxx.css
  source/shortcuts.rstext
Labels: enhancement

#315 Fix/remove broken links
  source/conf.py
  source/hardware/controllers/american_audio_vms4.rst
  source/hardware/controllers/behringer_cmd_micro.rst
  source/hardware/controllers/behringer_cmd_studio_4a.rst
  source/hardware/controllers/denon_dn_sc2000.rst
  source/hardware/controllers/hercules_djcontrol_jogvision.rst
  source/hardware/controllers/pioneer_ddj_sb.rst
  source/hardware/controllers/pioneer_ddj_sb2.rst
  source/hardware/controllers/pioneer_ddj_sx.rst
  source/hardware/controllers/reloop_beatpad.rst
  source/hardware/controllers/reloop_jockey_3_master_edition.rst
  source/hardware/controllers/soundless_studio_joymidi.rst
  source/hardware/controllers/stanton_djc_4.rst
  source/hardware/controllers/vestax_vci_300.rst
Labels: bug

#316 Controller cleanup
  source/_static/controllers/behringer_cmd_studio_4a_layout.png
  source/_static/controllers/behringer_cmd_studio_4a_top.png
  source/_static/controllers/behringer_cmd_studio_4a_top.svg
  source/hardware/controllers/behringer_cmd_studio_4a.rst
  source/hardware/controllers/vestax_vci_300.rst
Labels: controllers

#253 document intro and outro markers
  source/_static/Mixxx-200-Latenight-Deck-intro-outro.png
  source/_static/autodj-align-ends.png
  source/_static/autodj-align-starts.png
  source/_static/autodj-fade-at-outro-start.png
  source/_static/ends-aligned-waveforms.png
  source/_static/intro-outro-full.png
  source/_static/intro-start-outro-end.png
  source/_static/outro-right-click.png
  source/chapters/djing_with_mixxx.rst
  source/chapters/user_interface.rst
Labels: enhancement, outreachy

#326 document play_latched, + some small improvements
  source/chapters/advanced_topics.rst
Labels: basic info, enhancement

#332 Link fixes
  source/conf.py
  source/hardware/controllers/american_audio_vms2.rst
  source/hardware/controllers/behringer_b_control_deejay_bcd2000.rst
  source/hardware/controllers/behringer_cmd_mm_1.rst
  source/hardware/controllers/denon_mc4000.rst
  source/hardware/controllers/denon_mc6000mk2.rst
  source/hardware/controllers/dj_tech_cdj_101.rst
  source/hardware/controllers/dj_tech_djm_101.rst
  source/hardware/controllers/gemini_firstmix.rst
  source/hardware/controllers/hercules_djcontrol_air.rst
  source/hardware/controllers/hercules_djcontrol_jogvision.rst
  source/hardware/controllers/kontrol_dj_kdj500.rst
  source/hardware/controllers/korg_kaoss_dj.rst
  source/hardware/controllers/korg_nanokontrol.rst
  source/hardware/controllers/korg_nanokontrol2.rst
  source/hardware/controllers/nintendo_wiimote.rst
  source/hardware/controllers/numark_mixtrack_platinum.rst
  source/hardware/controllers/numark_v7.rst
  source/hardware/controllers/pioneer_cdj_350.rst
  source/hardware/controllers/pioneer_ddj_sx.rst
  source/hardware/controllers/reloop_beatmix_2.rst
  source/hardware/controllers/reloop_beatmix_4.rst
  source/hardware/controllers/reloop_beatpad.rst
  source/hardware/controllers/sony_sixxaxis.rst
  source/hardware/controllers/soundless_studio_joymidi.rst
  source/hardware/controllers/vestax_vci_100mkii.rst
Labels: bug

#334 Broken links 2.2
  source/chapters/hardware.rst
  source/conf.py
Labels: bug
