Repository mixxxdj/manual, pull requests merged in 2020-11, with the labels that each got.

#237 Update for DDJ-200 4-deck mode
  source/hardware/controllers/pioneer_ddj_200.rst
Labels: controllers

#275 Fix multi-language Sphinx PDF build
  .travis.yml
  build_pdf.sh
  source/conf.py
Labels: bug

#263 fixed broken links
  source/chapters/appendix.rst
  source/chapters/hardware.rst
  source/chapters/library.rst
  source/chapters/livebroadcasting.rst
Labels: bug, outreachy

#239 GitHub Actions: Add linkcheck job
  .github/workflows/linkcheck.yml
  source/conf.py
Labels: enhancement

#154 Updated screenshots and descriptions to fit 2.2.x Deere skin
  source/_static/2.2/crossfader.png
  source/_static/2.2/cue-controls.png
  source/_static/2.2/deere-parallel-waveforms.png
  source/_static/2.2/deere-separate-waveforms.png
  source/_static/2.2/expansion-buttons-skin-settings.png
  source/_static/2.2/expansion-buttons-top.png
  source/_static/2.2/gain-knob.png
  source/_static/2.2/headphone-button.png
  source/_static/2.2/hot-cue-controls.png
  source/_static/2.2/interface-decks.png
  source/_static/2.2/key-options.png
  source/_static/2.2/latenight-parallel-waveforms.png
  source/_static/2.2/loop-controls.png
  source/_static/2.2/microphone-section.png
  source/_static/2.2/mixer-section.png
  source/_static/2.2/options-button-grid.png
  source/_static/2.2/overview.png
  source/_static/2.2/preview-deck-section.png
  source/_static/2.2/sampler-section.png
  source/_static/2.2/sync-and-rate-controls.png
  source/_static/2.2/track-information.png
  source/_static/2.2/transport-controls.png
  source/_static/2.2/vinyl-control-mode.png
  source/_static/Mixxx-111-Deere-Deck-Vinyl-Mode.png
  source/_static/Mixxx-111-Deere-Microphone.png
  source/_static/Mixxx-111-Deere-Mixer-PFL.png
  source/_static/Mixxx-200-Deere-separate-waveform.png
  source/_static/Mixxx-200-Latenight-Bottom-Expansion-Buttons.png
  source/_static/Mixxx-200-Latenight-Deck-Button-Grid.png
  source/_static/Mixxx-200-Latenight-Deck-Hotcues.png
  source/_static/Mixxx-200-Latenight-Deck-Loops.png
  source/_static/Mixxx-200-Latenight-Deck-Playback.png
  source/_static/Mixxx-200-Latenight-Deck-Rate-Control.png
  source/_static/Mixxx-200-Latenight-Deck-Track-Info.png
  source/_static/Mixxx-200-Latenight-Deck-Transport.png
  source/_static/Mixxx-200-Latenight-Deck.png
  source/_static/Mixxx-200-Latenight-Mixer-Crossfader.png
  source/_static/Mixxx-200-Latenight-Mixer-EQ.png
  source/_static/Mixxx-200-Latenight-Mixer.png
  source/_static/Mixxx-200-Latenight-Preview-Deck.png
  source/_static/Mixxx-200-Latenight-Sampler-Deck.png
  source/_static/Mixxx-200-Latenight-Top-Expansion-Buttons.png
  source/_static/Mixxx-200-Latenight-parallel-waveform.png
  source/_static/Mixxx-200-Latenight.png
  source/_static/key_options.png
  source/chapters/user_interface.rst
Labels: enhancement, outreachy

#280 Netlify: Allow unsafe-inline scripts to accomodate RTD Theme
  netlify.toml
Labels: bug

#284 Roland DJ-505: Fix AUTO LOOP button documentation
  source/hardware/controllers/roland_dj_505.rst
Labels: controllers

#283 source/_templates/download: Fix PDF download link
  source/_templates/download.html
Labels: bug

#287 Describe the relink function better
  source/chapters/preferences.rst
Labels: enhancement, outreachy

#292 Travis CI: Improve PDF manual deploy path
  source/_templates/download.html
  travis-deploy.sh
Labels: enhancement

#298 Stanton SCS.3d: Don't use a GIF for circle mode
  source/_static/controllers/stanton_scs3d_circlemode.gif
  source/_static/controllers/stanton_scs3d_circlemode.jpg
  source/hardware/controllers/stanton_scs3d.rst
Labels: controllers

#296 chapters/advanced_topics: Fix broken coref to reloop_toggle
  source/chapters/advanced_topics.rst
Labels: bug

#243 Roland DJ-505: Document Saved Loop Mode
  source/hardware/controllers/roland_dj_505.rst
Labels: controllers

#247 Added microphone ducking documentation
  source/_static/2.2/microphone-ducking.png
  source/chapters/microphones.rst
Labels: basic info, outreachy

#299 Use sphinxcontrib.rsvgconverter instead of sphinx.ext.imgconverter
  .travis.yml
  requirements.txt
  source/conf.py
Labels: enhancement

#297 Numark Mixtrack Pro 3: Replace layout image GIF with SVG
  source/_static/controllers/numark_mixtrack_pro_3.gif
  source/_static/controllers/numark_mixtrack_pro_3.svg
  source/hardware/controllers/numark_mixtrack_pro_3.rst
Labels: controllers, enhancement

#248 Improve emphasis of keyboard shortcuts
  source/_static/css/mixxx.css
  source/chapters/appendix.rst
  source/chapters/library.rst
Labels: enhancement, outreachy

#295 Move HTML builder to GitHub Actions
  .github/workflows/build.yml
  .travis.yml
Labels: enhancement

#306 GitHub Actions: Improve Sphinx checks on PRs
  .github/workflows/linkcheck.yml
  .github/workflows/pre-commit.yml
  .github/workflows/sphinx.yml
  netlify.toml
Labels: enhancement

#307 chapters/controlling_mixxx: Reorder controller preset instructions
  source/chapters/controlling_mixxx.rst
Labels: bug

#305 sphinx-mixxx: Mark extension as safe for parallel reading
  sphinx-mixxx/sphinx_mixxx/setup.py
Labels: bug

#257 htaccess: Redirect to new manual website (manual.mixxx.org)
  htaccess
Labels: enhancement
