Repository mixxxdj/manual, pull requests merged in 2020-10, with the labels that each got.

#156 Netlify: Add support for deploy previews for the 2.2 branch
  netlify.toml
  runtime.txt
Labels: enhancement

#216 Glossary improvements
  source/glossary.rst
Labels: enhancement

#155 Appendix fixes
  source/chapters/appendix.rst
Labels: enhancement

#227 Cleanup whitespace issues and fix typos in the manual-2.3.x branch
  source/_static/controllers/behringer_cmd_micro.svg
  source/_static/controllers/denon_mc4000_layout.svg
  source/_static/controllers/electrix_tweaker_blank_template.svg
  source/_static/controllers/electrix_tweaker_deck_controls.svg
  source/_static/controllers/electrix_tweaker_deck_shift.svg
  source/_static/controllers/electrix_tweaker_encoder_layers.svg
  source/_static/controllers/electrix_tweaker_global_controls.svg
  source/_static/controllers/electrix_tweaker_top_shift.svg
  source/_static/controllers/electrix_tweaker_vinyl_mode.svg
  source/_static/controllers/numark_n4.svg
  source/_static/controllers/roland_dj_505.svg
  source/_static/controllers/roland_dj_505_browser.svg
  source/_static/controllers/roland_dj_505_deck.svg
  source/_static/controllers/roland_dj_505_effects.svg
  source/_static/controllers/roland_dj_505_mixer.svg
  source/_templates/keyboard_mapping_sheet.svg
  source/chapters/library.rst
  source/hardware/controllers/denon_mc4000.rst
  source/hardware/controllers/denon_mc6000mk2.rst
  source/hardware/controllers/hercules_dj_console_rmx.rst
  source/hardware/controllers/hercules_dj_console_rmx2.rst
  source/hardware/controllers/hercules_djcontrol_air.rst
  source/hardware/controllers/hercules_djcontrol_inpulse_300.rst
  source/hardware/controllers/hercules_djcontrol_mp3_e2.rst
  source/hardware/controllers/hercules_p32_dj.rst
  source/hardware/controllers/m_audio_xponent.rst
  source/hardware/controllers/numark_mixtrack.rst
  source/hardware/controllers/numark_mixtrack_platinum.rst
  source/hardware/controllers/numark_mixtrack_pro.rst
  source/hardware/controllers/numark_mixtrack_pro_3.rst
  source/hardware/controllers/pioneer_ddj_sb.rst
  source/hardware/controllers/pioneer_ddj_sb2.rst
  source/hardware/controllers/pioneer_ddj_sx.rst
  source/hardware/controllers/reloop_beatmix_4.rst
  source/hardware/controllers/reloop_beatpad.rst
  source/hardware/controllers/reloop_terminal_mix_series.rst
  source/hardware/controllers/stanton_scs1m.rst
  source/hardware/controllers/vestax_vci_400.rst
Labels: bug

#224 Add :hwlabel: role
  source/_static/css/mixxx.css
  source/hardware/controllers/roland_dj_505.rst
  sphinx-mixxx/sphinx_mixxx/domains.py
  sphinx-mixxx/sphinx_mixxx/roles.py
  sphinx-mixxx/sphinx_mixxx/setup.py
Labels: controllers, enhancement

#228 chapters/advanced_topics: Remove unneeded prefix in front of versions
  source/chapters/advanced_topics.rst
Labels: enhancement

#229 chapters/advanced_topics: Improve Mixxx control documentation
  source/chapters/advanced_topics.rst
Labels: enhancement

#150 Documenting Imports from Serato
  source/_static/icons/ic_library_serato.png
  source/chapters/library.rst
  source/shortcuts.rstext
Labels: outreachy

#225 Backport warning fixes to 2.2 branch
  .tx/config
  README.md
  htaccess
  manual_guidelines.rst
  netlify.toml
  runtime.txt
  source/_static/mixxx-icon-logo-symbolic.svg
  source/chapters/controlling_mixxx.rst
  source/chapters/djing_with_mixxx.rst
  source/chapters/getting_started.rst
  source/chapters/introduction.rst
  source/chapters/preferences.rst
  source/chapters/quickstart.rst
  source/chapters/user_interface.rst
  source/glossary.rst
  source/index_developer.rst
  source/shortcuts.rstext
  source/todolist.rst
Labels: bug

#242 Roland DJ-505: Fix wrong control numbers on manual page
  source/hardware/controllers/roland_dj_505.rst
Labels: bug, controllers

#246 Updating instruction on accessing the Waveforms menu item
  source/chapters/user_interface.rst
Labels: outreachy

#135 Document Keyboard Shortcuts
  source/chapters/appendix.rst
  source/chapters/introduction.rst
  source/chapters/library.rst
  source/chapters/user_interface.rst
  source/glossary.rst
Labels: outreachy

#226 Add support for pre-commit framework
  .codespellignore
  .flake8
  .github/workflows/pre-commit.yml
  .gitignore
  .pre-commit-config.yaml
  .rstcheck.cfg
  fabfile.py
  pyproject.toml
  source/conf.py
Labels: enhancement

#134 Create hercules_djcontrol_jogvision.rst
  source/hardware/controllers/hercules_djcontrol_jogvision.rst
Labels: controllers

#249 pre-commit: Remove check-merge-conflict hook
  .pre-commit-config.yaml
Labels: bug

#250 Fix various issues introduced by recently merged PRs
  source/chapters/appendix.rst
  source/chapters/introduction.rst
  source/chapters/library.rst
  source/chapters/user_interface.rst
  source/glossary.rst
Labels: bug

#251 Fixes for 2.3 branch
  .rstcheck.cfg
  source/chapters/library.rst
  source/hardware/controllers/hercules_djcontrol_jogvision.rst
Labels: bug

#143 Edited chapter 3.1.5 Transport Controls.
  source/chapters/user_interface.rst
Labels: outreachy

#255 source/chapters/advanced_topics: Remove [AutoDJ],add_random_track control
  source/chapters/advanced_topics.rst
Labels: bug

#256 document [group],CloneFromSampler
  source/chapters/advanced_topics.rst
Labels: controllers

#259 source/chapters/user_interface: Fix trailing whitespace
  source/chapters/user_interface.rst
Labels: bug

#260 Netlify: Add 404 page and fix redirects
  build_html.sh
  source/404.rst
  source/index.rst
Labels: enhancement

#262 Mixxxcontrol improvements
  source/chapters/advanced_topics.rst
  source/glossary.rst
Labels: enhancement

#264 Native Instruments Traktor Kontrol S2 MK2: Fix markup
  source/hardware/controllers/native_instruments_traktor_kontrol_s2_mk2.rst
Labels: bug, controllers

#265 Fix Scrollbar in tables and prevent wrapping in :hwlabel:
  source/_static/css/mixxx.css
Labels: enhancement

#267 Add support for "main" branch
  .travis.yml
  source/conf.py
Labels: enhancement

#268 sphinx-mixxx: Fix usage of ampersand in hwlabel role
  sphinx-mixxx/sphinx_mixxx/roles.py
Labels: bug

#271 Netlify: Add security headers
  netlify.toml
Labels: enhancement
