Repository mixxxdj/manual, pull requests merged in 2021-04, with the labels that each got.

#373 Fix broken PDF layout
  source/hardware/controllers/denon_mc7000.rst
Labels: bug

#258 Added a link to glossary term: "crossfader" section 2.4.1
  source/chapters/getting_started.rst
Labels: outreachy

#309 Updated S4Mk2 manual with proposed changes from PR
  source/hardware/controllers/native_instruments_traktor_kontrol_s4_mk2.rst
Labels: controllers
